137 constant change
gemrb/gemrb pull request #1530
Opened 2022-01-29 03:45 UTC by rsantellan

## Description
Externalize the colors of the message to table. #137 

## Checklist

- [X] Commit messages are descriptive and explain the rationale for changes
- [X] I used the same coding style as the surrounding code 
- [X] I have tested the proposed changes
- [X] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

2022-01-29 05:00 UTC, bradallred requested changes

2022-01-29 08:59 UTC, lynxlynxlynx commented on gemrb/core/DisplayMessage.h
> +enum { DMC_DIALOG, DMC_DIALOGPARTY, DMC_GOLD, DMC_RED, DMC_BG2XPGREEN, DMC_LIGHTGREY, DMC_WHITE };
That's the plan, but I made him go slower to be clearer and to avoid conflicts with the utf-16 branch.

2022-01-29 10:06 UTC, lynxlynxlynx commented
Some of the DisplayMessage functions are now redundant. For example there's no need for all that indirection with DisplayRollStringName, since it never uses dynamic colors. So just change the original function, there's no need for a wrapper. Then do the same with any other such function.

2022-01-31 01:20 UTC, rsantellan commented on gemrb/unhardcoded/bg1/colors.2da
> +DIALOG_PARTY	0x8080ffff
I have change this to add the new line and better formatting.

2022-01-31 01:22 UTC, rsantellan commented on gemrb/core/DisplayMessage.h
> +	void DisplayConstantString(size_t stridx, const Color &color, Scriptable *speaker=NULL) const;
Change to nullptr instead of NULL

2022-01-31 01:23 UTC, rsantellan commented
> Some of the DisplayMessage functions are now redundant. For example there's no need for all that indirection with DisplayRollStringName, since it never uses dynamic colors. So just change the original function, there's no need for a wrapper. Then do the same with any other such function.

The DisplayRollStringName was like that, I don't really understand it fully so I didn't touch it. Will check which of the DisplayMessage are redundant.

2022-02-02 15:38 UTC, rsantellan commented
> > Some of the DisplayMessage functions are now redundant. For example there's no need for all that indirection with DisplayRollStringName, since it never uses dynamic colors. So just change the original function, there's no need for a wrapper. Then do the same with any other such function.
> 
> The DisplayRollStringName was like that, I don't really understand it fully so I didn't touch it. Will check which of the DisplayMessage are redundant.

I'm a little stuck with this part. Don't know how to improve it.

2022-02-02 16:48 UTC, lynxlynxlynx commented
Is anyone still calling
`void DisplayRollStringName(const String& fmt, unsigned char color, const Scriptable *speaker, ARGS&& ...args) const {` ? You should be able to merge it with the other function.

2022-02-03 11:35 UTC, rsantellan commented
> 
```
grep 'DisplayRollStringName' * -nr
gemrb/includes/ie_types.h:77:	// params to DisplayRollStringName
gemrb/core/GameScript/Actions.cpp:4562:		displaymsg->DisplayRollStringName(ieStrRef::ROLL12, DMC_LIGHTGREY, snd, 10+skill, roll+level, wismod);
gemrb/core/Scriptable/Container.cpp:193:			displaymsg->DisplayRollStringName(ieStrRef::ROLL11, DMC_LIGHTGREY, actor, stat-dexmod, LockDifficulty, dexmod);
gemrb/core/Scriptable/Container.cpp:232:		displaymsg->DisplayRollStringName(ieStrRef::ROLL1, DMC_LIGHTGREY, actor, roll, bonus, LockDifficulty);
gemrb/core/Scriptable/Scriptable.cpp:1147:		displaymsg->DisplayRollStringName(ieStrRef::ROLL21, DMC_LIGHTGREY, actor, roll, chance);
gemrb/core/Scriptable/Scriptable.cpp:1194:			displaymsg->DisplayRollStringName(ieStrRef::ROLL15, DMC_LIGHTGREY, detective, Spellcraft+IntMod, AdjustedSpellLevel, IntMod);
gemrb/core/Scriptable/Scriptable.cpp:1862:			displaymsg->DisplayRollStringName(ieStrRef::ROLL13, DMC_LIGHTGREY, detective, skill-bonus, TrapDetectionDiff, bonus);
gemrb/core/Scriptable/Actor.cpp:3626:		displaymsg->DisplayRollStringName(ieStrRef::ROLL22, DMC_LIGHTGREY, this, roll, save, modifier, spellLevel, saveBonus);
gemrb/core/Scriptable/Actor.cpp:3630:		displaymsg->DisplayRollStringName(ieStrRef::ROLL23, DMC_LIGHTGREY, this, roll, save, modifier, spellLevel, saveBonus);
gemrb/core/Scriptable/Actor.cpp:4363:		displaymsg->DisplayRollStringName(ieStrRef::ROLL19, DMC_LIGHTGREY, this, roll, concentration, bonus, damage, spellLevel);
gemrb/core/Scriptable/Actor.cpp:4415:			displaymsg->DisplayRollStringName(ieStrRef::ROLL20, DMC_LIGHTGREY, this, ToHit.GetTotal());
gemrb/core/Scriptable/Actor.cpp:9235:	displaymsg->DisplayRollStringName(ieStrRef::ROLL14, DMC_LIGHTGREY, this, skill + roll, level + 20, level);
gemrb/core/Scriptable/Actor.cpp:9399:			displaymsg->DisplayRollStringName(ieStrRef::ROLL18, DMC_LIGHTGREY, this, sneakAttackDamage);
gemrb/core/Scriptable/Actor.cpp:9404:			displaymsg->DisplayRollStringName(ieStrRef::ROLL17, DMC_LIGHTGREY, this, sneakAttackDamage);
gemrb/core/Scriptable/Actor.cpp:9418:		//displaymsg->DisplayRollStringName(25053, DMC_LIGHTGREY, this, extraDamage);
gemrb/core/Scriptable/Actor.cpp:10663:			displaymsg->DisplayRollStringName(ieStrRef::ROLL10, DMC_LIGHTGREY, actor, skill-bonus, roll, bonus);
gemrb/core/Scriptable/Actor.cpp:10667:			displaymsg->DisplayRollStringName(ieStrRef::ROLL8, DMC_LIGHTGREY, actor, skill, targetDC, roll);
gemrb/core/Scriptable/Actor.cpp:10671:			displaymsg->DisplayRollStringName(ieStrRef::ROLL7, DMC_LIGHTGREY, actor, skill, targetDC, roll);
gemrb/core/Scriptable/Actor.cpp:10772:	displaymsg->DisplayRollStringName(ieStrRef::ROLL9, DMC_LIGHTGREY, this, skill/7, roll, GetAbilityBonus(IE_DEX));
gemrb/core/Scriptable/Actor.cpp:10810:			displaymsg->DisplayRollStringName(ieStrRef::ROLL2, DMC_LIGHTGREY, this, skill, targetDC, roll);
gemrb/core/Scriptable/Actor.cpp:10837:			displaymsg->DisplayRollStringName(ieStrRef::ROLL0, DMC_LIGHTGREY, this, skill, targetDC, roll);
gemrb/core/Scriptable/Actor.cpp:11201:			displaymsg->DisplayRollStringName(ieStrRef::ROLL4, DMC_LIGHTGREY, this, roll + concentration, 15 + spellLevel, bonus);
gemrb/core/Scriptable/Actor.cpp:11203:			displaymsg->DisplayRollStringName(ieStrRef::ROLL5, DMC_LIGHTGREY, this);
gemrb/core/Scriptable/Actor.cpp:11209:			displaymsg->DisplayRollStringName(ieStrRef::ROLL3, DMC_LIGHTGREY, this, roll + concentration, 15 + spellLevel, bonus);
gemrb/core/Scriptable/Door.cpp:351:			displaymsg->DisplayRollStringName(ieStrRef::ROLL6, DMC_LIGHTGREY, actor, roll, skill-bonus, bonus, trapDC);
gemrb/core/Scriptable/Door.cpp:363:			displaymsg->DisplayRollStringName(ieStrRef::ROLL6, DMC_LIGHTGREY, actor, roll, skill-bonus, bonus, trapDC);
gemrb/core/Scriptable/Door.cpp:390:			displaymsg->DisplayRollStringName(ieStrRef::ROLL11, DMC_LIGHTGREY, actor, stat-dexmod, LockDifficulty, dexmod);
gemrb/core/Scriptable/Door.cpp:429:		displaymsg->DisplayRollStringName(ieStrRef::ROLL1, DMC_LIGHTGREY, actor, roll, bonus, LockDifficulty);
gemrb/core/DisplayMessage.h:61:	void DisplayRollStringName(const String& fmt, unsigned char color, const Scriptable *speaker, ARGS&& ...args) const {
gemrb/core/DisplayMessage.h:112:	void DisplayRollStringName(ieStrRef stridx, unsigned char color, const Scriptable *speaker, ARGS&& ...args) const {
gemrb/core/DisplayMessage.h:115:			DisplayRollStringName(fmt, color, speaker, std::forward<ARGS>(args)...);
gemrb/core/EffectQueue.cpp:1020:		displaymsg->DisplayRollStringName(ieStrRef::ROLL16, DMC_LIGHTGREY, actor, val, roll, fx->CasterLevel, penetration);
```
I have does, the idea is change that for this: **DisplayStringName** ? What I do with the extra arguments ?

2022-02-03 14:47 UTC, lynxlynxlynx commented
I don't see any user there, besides the one it should be merged with — all take a ieStrRef.

btw, `git grep` is very handy for grepping in git trees.

2022-02-07 12:18 UTC, rsantellan commented
> I don't see any user there, besides the one it should be merged with — all take a ieStrRef.
> 
> btw, `git grep` is very handy for grepping in git trees.

Remove the private one and use only the public one, the thing that really complicates me is the **String formatted = fmt::format(fmt, std::forward<ARGS>(args)...);** don't know how to change it to call to other functions.

2022-02-07 13:09 UTC, lynxlynxlynx commented
The last commit looks good. 👌 There's no need for that line to call any other function, it's basically a printf call.

2022-02-07 13:15 UTC, lynxlynxlynx commented
Now you can check if any other function can be removed, since you added many new ones earlier.

2022-02-07 18:56 UTC, lynxlynxlynx commented
If I had to guess, I'd say that's a consequence of displaymsg's external linkage with no visibility limits.

2022-02-08 02:45 UTC, rsantellan commented
> If I had to guess, I'd say that's a consequence of displaymsg's external linkage with no visibility limits.

I double check all the functions and was able to remove a few of them, but a lot of them didn't want to change them because was used in other parts of the code.

2022-02-11 17:05 UTC, lynxlynxlynx commented on gemrb/core/DisplayMessage.h
> +	void DisplayString(ieStrRef stridx, unsigned char color, STRING_FLAGS flags) const;
If you resolve the strref in GemRB_DisplayString, this one can go. Same for the variant of DisplayStringName that it is using.

2022-02-11 17:08 UTC, lynxlynxlynx commented on gemrb/core/DisplayMessage.h
>  	void DisplayString(String text, const Color &color, Scriptable *target) const;
This one can be private now.

2022-02-24 14:12 UTC, rsantellan commented
@lynxlynxlynx I did a merge of the master to fix the problems but I believe now it was a mistake... Let me know how to improve it.

2022-02-24 14:59 UTC, lynxlynxlynx commented
Oh no, it's indeed a mess. Next time use a rebase (eg. git pull --rebase) to avoid this, I'm not sure if it's trivially solvable. You could try rebasing now, but I don't know if it would work.

What should either way is creating a new branch and cherry picking you work on top, commit by commit. Something like:
```bash
# - assuming your local "master" branch is up to date with our upstream one
# 1. filter out your own commits; this should print the commit SHAs that are not yet on master
git cherry master

# 2. create a fresh branch from master
git checkout -b 137-colors master

# 3. start copying the work over
# run this for each commit found in 1.
git cherry-pick the-commit-sha

# 4. testing

# 5. open a fresh PR with the new branch

# 6. delete the old branch
# git branch -D 137-constant-change
```

2022-02-25 01:45 UTC, rsantellan commented
I have created a new PR https://github.com/gemrb/gemrb/pull/1575

I did it by hand because the rebase was a total mess.

On Thu, Feb 24, 2022 at 12:00 PM Jaka Kranjc ***@***.***>
wrote:

> Oh no, it's indeed a mess. Next time use a rebase (eg. git pull --rebase)
> to avoid this, I'm not sure if it's trivially solvable. You could try
> rebasing now, but I don't know if it would work.
>
> What should either way is creating a new branch and cherry picking you
> work on top, commit by commit. Something like:
>
> # - assuming your local "master" branch is up to date with our upstream one
> # 1. filter out your own commits; this should print the commit SHAs that are not yet on master
> git cherry master
>
> # 2. create a fresh branch from master
> git checkout -b 137-colors master
>
> # 3. start copying the work over
> # run this for each commit found in 1.
> git cherry-pick the-commit-sha
>
> # 4. testing
>
> # 5. open a fresh PR with the new branch
>
> # 6. delete the old branch
> # git branch -D 137-constant-change
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gemrb/gemrb/pull/1530#issuecomment-1049946684>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAN4PNUKR7JKZNIRDTYVAY3U4ZBXJANCNFSM5NCLKRXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-25 19:11 UTC, closed without merging